{{- if and (or .Values.controllers.cronjob.enabled .Values.controllers.job.enabled) .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cnpg-backup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg-backup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cnpg-backup.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ if .Values.rbac.serviceAccountName }}{{ .Values.rbac.serviceAccountName }}{{ else }}{{ include "cnpg-backup.fullname" . }}{{ end }}
    namespace: {{ .Release.Namespace }}
{{- end }}