apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pgdump-test
type: Opaque
stringData:
  user: testuser
  password: testpassword
  host: postgres-service.pgdump-test.svc.cluster.local
  port: "5432"
  dbname: testdb