apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgdump-backup
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ADORSYS-GIS/ai-helm.git
    targetRevision: fix/pgdump-backup
    path: charts/pgdump-backup
    helm:
      releaseName: pgdump-backup
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: litellm

  syncPolicy:
    syncOptions:
      - ServerSideApply=true

  revisionHistoryLimit: 2
