apiVersion: v1
kind: Secret
metadata:
  name: open-web-ui-s3
  namespace: default
type: Opaque
stringData:
  S3_BUCKET_NAME: "my-postgres-backups"
  S3_ACCESS_KEY_ID: "dummy_access_key"
  S3_SECRET_ACCESS_KEY: "dummy_secret_key"
  S3_REGION_NAME: "us-east-1"

