apiVersion: v1
kind: Secret
metadata:
  name: litellm-pg-app
  namespace: default
type: Opaque
stringData:
  host: "postgres.pgdump-test.svc.cluster.local"
  port: "5432"
  dbname: "testdb"
  username: "testuser"
  password: "testpassword"